version: '3'
services:
  nfsen:
    build: nfsen-ng
    ports:
    - 8080:80
    volumes:
    - ./profiles-data:/var/nfdump/profiles-data
    - ./sources.conf:/tmp/sources.conf:ro
    restart: unless-stopped
  nfdump:
    build: nfdump
    ports:
    - 9000-9001:9000-9001/udp
    volumes:
    - ./profiles-data:/data
    - ./sources.conf:/tmp/sources.conf:ro
    restart: unless-stopped
